server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  # SPA fallback
  location / {
    try_files $uri $uri/ /index.html;
  }

  # Proxy a Prometheus dentro de la red docker
  location /prom/ {
    proxy_pass http://prometheus:9090/;
    proxy_set_header Host $host;
    proxy_buffering off;
  }

  # Proxy a Elasticsearch
  location /es/ {
    proxy_pass http://elasticsearch:9200/;
    proxy_set_header Host $host;
    proxy_set_header Content-Type application/json;
  }

  # Proxy a Ollama (corre en el host, no en docker)
  # host.docker.internal funciona en Docker Desktop (Windows y Mac)
  location /ollama/ {
    proxy_pass http://host.docker.internal:11434/;
    proxy_set_header Host $host;
    proxy_read_timeout 300s;
    proxy_send_timeout 300s;
  }

  # Proxy a la API de e-commerce
  location /api/ {
    proxy_pass http://ecommerce-api:3000/api/;
    proxy_set_header Host $host;
  }
}
